### ISSUE TITLE
Training config or Code for other datasets like CUB, CelebA-5 and ImageNet-LT

### ISSUE THREAD

**Issue by srikesh-07** [qym7/CBDM-pytorch#4]
Dear Authors,

My heartful appreciation for your great work.

As mentioned in your research paper, I need to reproduce the results of CUB, CelebA-5, and ImageNet-LT. As per the title suggests, Can you please provide us the code or configuration file for training the following datasets,

1. CUB
2. CelebA-5
3. ImageNet_LT

I am eagerly waiting for your response.

Thank you

**Comment by qym7** [comment]
Hi, 

Thanks for your question. Unfortunately, due to the fact that corresponding files have been removed, it is no longer possible to give the exact configurations. 
The only hyperparameters we still have, and I believe the most important ones (omega and tau) are reported in the appendix for those 3 datasets. 
Hope to be helpful. 

Best, 



From: "Srikeshram" ***@***.***> 
To: "qym7/CBDM-pytorch" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Sent: Friday, January 19, 2024 11:54:09 AM 
Subject: [qym7/CBDM-pytorch] Training Config or Code for other datasets like CUB, CelebA-5 and ImageNet-LT (Issue #4) 





Dear Authors, 

My heartful appreciation for your great work. 

As mentioned in your research paper, I need to reproduce the results of CUB, CelebA-5, and ImageNet-LT. As per the title suggests, Can you please provide us the code or configuration file for training the following datasets, 

    1. CUB 
    2. CelebA-5 
    3. ImageNet_LT 


I am eagerly waiting for your response. 

Thank you
